# Generated by Django 3.0.5 on 2020-04-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehrender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lehrveranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lehrt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Studentverwaltung.Lehrender')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrikel_nr', models.CharField(max_length=10)),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('besucht', models.ManyToManyField(to='Studentverwaltung.Lehrveranstaltung')),
            ],
        ),
    ]
