# Generated by Django 3.0.5 on 2020-04-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='besucht',
        ),
        migrations.AddField(
            model_name='lehrveranstaltung',
            name='besucht',
            field=models.ManyToManyField(to='Studentverwaltung.Student'),
        ),
    ]
