# Generated by Django 3.0.5 on 2020-04-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentverwaltung', '0002_auto_20200417_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrender',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
